    var teamCity = ["Baltimore",
        "Boston",
        "Breckenridge",
        "Canada",
        "Charleston",
        "Chicago",
        "Dallas",
        "Hades",
        "Hawaii",
        "Hellmouth",
        "Houston",
        "Kansas City",
        "Los Angeles",
        "Mexico City",
        "Miami",
        "New York",
        "Philly",
        "San Francisco",
        "Seattle",
        "Yellowstone"
    ];

    var teamName = ["Breath Mints",
        "Crabs",
        "Dalé",
        "Firefighters",
        "Flowers",
        "Fridays",
        "Garages",
        "Jazz Hands",
        "Lovers",
        "Magic",
        "Millennials",
        "Moist Talkers",
        "Pies",
        "Shoe Thieves",
        "Spies",
        "Steaks",
        "Sunbeams",
        "Tacos",
        "Tigers",
        "Wild Wings"
    ];

    var colors = ["593037",
        "6388AD",
        "780018",
        "FFD4D8",
        "8C2A3E",
        "178F55",
        "5C1C1C",
        "2B4075",
        "8C8D8F",
        "F5FEFF",
        "F7D1FF",
        "FFFBAB",
        "67556B",
        "9141BA",
        "64376E",
        "399D8F",
        "D15700",
        "FFCE0A",
        "BF0043",
        "3EE652"
    ];

    var emoji = [
        "🍬",
        "🦀",
        "🚤",
        "🔥",
        "🌹",
        "🏝",
        "🎸",
        "👐",
        "💋",
        "✨",
        "📱",
        "🗣",
        "🥧",
        "👟",
        "🕵",
        "🥩",
        "🌞",
        "🌮",
        "🐅",
        "🍗"
    ];