var genres = [
    "Blues",
    "Country",
    "Electronic",
    "House",
    "Folk",
    "Hip hop",
    "Jazz",
    "Pop",
    "R&B",
    "Soul",
    "Rock",
    "Heavy Metal",
    "Punk Rock"
]

var genres2 = [
    "Blues",
    "Country",
    "Electronic",
    "Disco",
    "Dance",
    "Electronica",
    "Trap",
    "Industrial",
    "Techno",
    "Trance",
    "House",
    "Pop Rock",
    "Folk",
    "Hip hop",
    "Jazz",
    "Pop",
    "R&B",
    "Soul",
    "Rock",
    "Metal",
    "Punk Rock",
    "Funk",
    "Rap",
    "Psychedelic",
    //"Ska"
]

// debug
//var genres2 = ["R&B"]

var langs = [
    "Afghan",
    "Albanian",
    "Algerian",
    "Andorran",
    "Angolan",
    "Argentinian",
    "Armenian",
    "Australian",
    "Austrian",
    "Azerbaijani",
    "Bahamian",
    "Bangladeshi",
    "Bahraini",
    "Barbadian",
    "Belorussian",
    "Belgian",
    "Beninese",
    "Bhutanese",
    "Bolivian",
    "Bosnian",
    "Brazilian",
    "Briton",
    "Bruneian",
    "Bulgarian",
    "Burmese",
    "Burkinese",
    "Burundian",
    "Cambodian",
    "Cameroonian",
    "Canadian",
    "Cape Verdean",
    "Chadian",
    "Chilean",
    "Chinese",
    "Colombian",
    "Congolese",
    "Costa Rican",
    "Croatian",
    "Cuban",
    "Cypriot",
    "Czech",
    "Danish",
    "Djiboutian",
    "Dominican",
    "Ecuadorean",
    "Egyptian",
    "Salvadorean",
    "Eritrean",
    "Estonian",
    "Ethiopian",
    "Fijian",
    "Finnish",
    "French",
    "Gabonese",
    "Gambian",
    "Georgian",
    "German",
    "Ghanaian",
    "Greek",
    "Grenadian",
    "Guatemalan",
    "Guinean",
    "Guyanese",
    "Haitian",
    "Dutch",
    "Honduran",
    "Hungarian",
    "Icelandic",
    "Indian",
    "Indonesian",
    "Iranian",
    "Iraqi",
    "Irish",
    "Italian",
    "Jamaican",
    "Japanese",
    "Jordanian",
    "Kazakh",
    "Kenyan",
    "Kuwaiti",
    "Laotian",
    "Latvian",
    "Lebanese",
    "Liberian",
    "Libyan",
    "Lithuanian",
    "Macedonian",
    "Madagascan",
    "Malawian",
    "Malaysian",
    "Maldivian",
    "Malian",
    "Maltese",
    "Mauritanian",
    "Mauritian",
    "Mexican",
    "Moldovan",
    "Monacan",
    "Mongolian",
    "Montenegrin",
    "Moroccan",
    "Mozambican",
    "Namibian",
    "Nepalese",
    "Dutch",
    "New Zealand ",
    "Nicaraguan",
    "Nigerien",
    "Nigerian",
    "North Korean",
    "Norwegian",
    "Omani",
    "Pakistani",
    "Panamanian",
    "Guinean",
    "Paraguayan",
    "Peruvian",
    "Filipino",
    "Polish",
    "Portuguese",
    "Qatari",
    "Romanian",
    "Russian",
    "Rwandan",
    "Saudi",
    "Scottish",
    "Senegalese",
    "Serbian",
    "Seychellois",
    "Sierra Leonian",
    "Singaporean",
    "Slovak",
    "Slovenian",
    "Somali",
    "South African",
    "South Korean",
    "Spanish",
    "Sri Lankan",
    "Sudanese",
    "Surinamese",
    "Swazi",
    "Swedish",
    "Swiss",
    "Syrian",
    "Taiwanese",
    "Tajik",
    "Tanzanian",
    "Thai",
    "Togolese",
    "Trinidadian",
    "Tobagan",
    "Tobagonian",
    "Tunisian",
    "Turkish",
    "Turkoman",
    "Tuvaluan",
    "Ugandan",
    "Ukrainian",
    "UAE",
    "British",
    "American",
    "Uruguayan",
    "Uzbek",
    "Vanuatuan",
    "Venezuelan",
    "Vietnamese",
    "Welsh",
    "Western Samoan",
    "Yemeni",
    "Yugoslav",
    "Zaïrean",
    "Zambian",
    "Zimbabwean"
]